export default class DomString {
  get className() {
    return {};
  }
  get id() {
    return {
      acceptTerm: "term",
      avatar: "avatar-wrap",
      avatarVal: "avatar-img",
      birthDate: "birth-date",
      botSect: "bot-sect",
      btnWrap: "btn-wrap",
      confirmPassword: "confirm-password",
      confirmPasswordValidate: "confirm-password-validate",
      discard: "discard",
      female: "female",
      file: "file",
      home: "home",
      leftPart: "left-part",
      login: "login",
      mail: "mail",
      mailValidate: "mail-validate",
      male: "male",
      midSect: "mid-sect",
      navWrap: "nav-wrap",
      password: "password",
      passwordValidate: "password-validate",
      phone: "phone",
      phoneValidate: "phone-validate",
      register: "register",
      rightPart: "right-part",
      signUp: "sign-up",
      signUpPage: "signup-page",
      signUpTitle: "signup-title",
      signUpWrap: "s-wrap",
      smallPart: "small-part",
      textFemale: "text-female",
      textMale: "text-male",
      topSect: "top-sect",
      upload: "upload",
      username: "username",
      usernameValidate: "username-validate",
      q: {
        acceptTerm: "#term",
        avatar: "#avatar-wrap",
        birthDate: "#birth-date",
        botSect: "#bot-sect",
        btnWrap: "#btn-wrap",
        confirmPassword: "#confirm-password",
        confirmPasswordValidate: "#confirm-password-validate",
        discard: "#discard",
        female: "#female",
        file: "#file",
        home: "#home",
        leftPart: "#left-part",
        login: "#login",
        mail: "#mail",
        mailValidate: "#mail-validate",
        male: "#male",
        midSect: "#mid-sect",
        navWrap: "#nav-wrap",
        password: "#password",
        passwordValidate: "#password-validate",
        phone: "#phone",
        phoneValidate: "#phone-validate",
        register: "#register",
        rightPart: "#right-part",
        signUp: "#sign-up",
        signUpPage: "#signup-page",
        signUpTitle: "#signup-title",
        signUpWrap: "#s-wrap",
        smallPart: "#small-part",
        textFemale: "#text-female",
        textMale: "#text-male",
        topSect: "#top-sect",
        upload: "#upload",
        username: "#username",
        usernameValidate: "#username-validate",
      },
    };
  }
}
