export default class DomString {
  get className() {
    return {};
  }
  get id() {
    return {
      avatar: "avatar-wrap",
      birthDate: "birth-date",
      botSect: "bot-sect",
      btnWrap: "btn-wrap",
      discard: "discard",
      female: "female",
      file: "file",
      home: "home",
      leftPart: "left-part",
      login: "login",
      male: "male",
      midSect: "mid-sect",
      navWrap: "nav-wrap",
      rightPart: "right-part",
      signUp: "sign-up",
      signUpPage: "signup-page",
      signUpTitle: "signup-title",
      signUpWrap: "s-wrap",
      smallPart: "small-part",
      textFemale: "text-female",
      textMale: "text-male",
      topSect: "top-sect",
      upload: "upload",
      q: {
        avatar: "#avatar-wrap",
        birthDate: "#birth-date",
        botSect: "#bot-sect",
        btnWrap: "#btn-wrap",
        discard: "#discard",
        female: "#female",
        file: "#file",
        home: "#home",
        leftPart: "#left-part",
        login: "#login",
        male: "#male",
        midSect: "#mid-sect",
        navWrap: "#nav-wrap",
        rightPart: "#right-part",
        signUp: "#sign-up",
        signUpPage: "#signup-page",
        signUpTitle: "#signup-title",
        signUpWrap: "#s-wrap",
        smallPart: "#small-part",
        textFemale: "#text-female",
        textMale: "#text-male",
        topSect: "#top-sect",
        upload: "#upload",
      },
    };
  }
}
